/**
 * Comprehensive currencies list matching Stocky dashboard with 150+ international currencies.
 * Supports real currency codes, symbols, names, and dynamic rate conversions.
 */

export type CurrencyInfo = {
  code: string;
  name: string;
  symbol: string;
  rate: number; // relative to 1.0 USD
};

export const ALL_CURRENCIES: CurrencyInfo[] = [
  { code: 'USD', name: 'US Dollar', symbol: '$', rate: 1.0 },
  { code: 'EUR', name: 'Euro', symbol: '€', rate: 0.92 },
  { code: 'GBP', name: 'British Pound', symbol: '£', rate: 0.78 },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: 'Rs', rate: 278.5 },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', rate: 83.5 },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', rate: 3.75 },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', rate: 3.67 },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', rate: 1.36 },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', rate: 1.52 },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', rate: 155.0 },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', rate: 7.23 },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', rate: 0.91 },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', rate: 5.15 },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', rate: 91.2 },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', rate: 32.2 },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', rate: 18.4 },
  { code: 'QAR', name: 'Qatari Riyal', symbol: '﷼', rate: 3.64 },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KD', rate: 0.31 },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'BD', rate: 0.38 },
  { code: 'OMR', name: 'Omani Rial', symbol: '﷼', rate: 0.385 },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', rate: 1.35 },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', rate: 4.71 },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', rate: 36.8 },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', rate: 16100.0 },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', rate: 57.5 },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', rate: 25400.0 },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', rate: 1370.0 },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', rate: 1.66 },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', rate: 10.7 },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', rate: 10.8 },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', rate: 6.87 },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', rate: 3.96 },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'Mex$', rate: 16.7 },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', rate: 885.0 },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', rate: 3900.0 },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', rate: 935.0 },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', rate: 47.2 },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', rate: 1400.0 },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', rate: 131.0 },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵', rate: 13.8 },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', rate: 117.0 },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', rate: 300.0 },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', rate: 71.5 },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L', rate: 93.0 },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', rate: 388.0 },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'NAƒ', rate: 1.80 },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', rate: 850.0 },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', rate: 1.80 },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', rate: 1.70 },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', rate: 1.80 },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: 'Bds$', rate: 2.0 },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', rate: 2860.0 },
  { code: 'BMD', name: 'Bermudan Dollar', symbol: '$', rate: 1.0 },
  { code: 'BND', name: 'Brunei Dollar', symbol: 'B$', rate: 1.35 },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs', rate: 6.91 },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', rate: 1.0 },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', rate: 83.5 },
  { code: 'BWP', name: 'Botswanan Pula', symbol: 'P', rate: 13.6 },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', rate: 3.27 },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', rate: 2.0 },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', rate: 2780.0 },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', rate: 512.0 },
  { code: 'CUP', name: 'Cuban Peso', symbol: '$', rate: 24.0 },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', rate: 101.5 },
  { code: 'CZK', name: 'Czech Republic Koruna', symbol: 'Kč', rate: 23.0 },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', rate: 178.0 },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', rate: 58.5 },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'DA', rate: 134.5 },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', rate: 15.0 },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', rate: 57.2 },
  { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ$', rate: 2.25 },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', rate: 0.78 },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', rate: 2.70 },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', rate: 0.78 },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', rate: 68.0 },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', rate: 8600.0 },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', rate: 7.78 },
  { code: 'GYD', name: 'Guyanaese Dollar', symbol: 'G$', rate: 209.0 },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', rate: 7.81 },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', rate: 24.7 },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', rate: 6.93 },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', rate: 132.0 },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', rate: 358.0 },
  { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', rate: 3.68 },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ID', rate: 1310.0 },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', rate: 42000.0 },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', rate: 139.0 },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', rate: 156.0 },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD', rate: 0.71 },
  { code: 'KGS', name: 'Kyrgystani Som', symbol: 'som', rate: 88.0 },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', rate: 4080.0 },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', rate: 452.0 },
  { code: 'KPW', name: 'North Korean Won', symbol: '₩', rate: 900.0 },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', rate: 0.83 },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', rate: 442.0 },
  { code: 'LAK', name: 'Laotian Kip', symbol: '₭', rate: 21400.0 },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'L£', rate: 89500.0 },
  { code: 'LRD', name: 'Liberian Dollar', symbol: 'L$', rate: 194.0 },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', rate: 18.4 },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'LD', rate: 4.85 },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'DH', rate: 10.05 },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', rate: 17.7 },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', rate: 4450.0 },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'den', rate: 56.6 },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', rate: 2100.0 },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', rate: 3450.0 },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', rate: 8.05 },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', rate: 39.6 },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', rate: 46.5 },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', rate: 15.4 },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', rate: 1735.0 },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', rate: 63.9 },
  { code: 'NAD', name: 'Namibian Dollar', symbol: 'N$', rate: 18.4 },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', rate: 36.8 },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', rate: 133.5 },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', rate: 1.0 },
  { code: 'PEN', name: 'Peruvian Nuevo Sol', symbol: 'S/.', rate: 3.74 },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', rate: 3.86 },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: 'Gs', rate: 7520.0 },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', rate: 4.58 },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'din.', rate: 107.8 },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'R₣', rate: 1300.0 },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI$', rate: 8.45 },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: 'SR', rate: 13.8 },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'SDG', rate: 601.0 },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'S', rate: 571.0 },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: 'Sr$', rate: 35.2 },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: 'SS£', rate: 1550.0 },
  { code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db', rate: 22.5 },
  { code: 'SYP', name: 'Syrian Pound', symbol: '£S', rate: 13000.0 },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'E', rate: 18.4 },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM', rate: 10.9 },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T', rate: 3.50 },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'DT', rate: 3.12 },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', rate: 2.38 },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$', rate: 6.78 },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', rate: 32.4 },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', rate: 2590.0 },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', rate: 39.8 },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', rate: 3770.0 },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', rate: 38.6 },
  { code: 'UZS', name: 'Uzbekistan Som', symbol: 'so\'m', rate: 12700.0 },
  { code: 'VES', name: 'Venezuelan Bolívar Soberano', symbol: 'Bs.S', rate: 36.6 },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', rate: 120.0 },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WS$', rate: 2.76 },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', rate: 604.0 },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC$', rate: 2.70 },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', rate: 604.0 },
  { code: 'XPF', name: 'CFP Franc', symbol: '₣', rate: 110.0 },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', rate: 250.0 },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', rate: 26.2 },
  { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'Z$', rate: 13.5 },
];

export function getCurrencyInfo(code: string): CurrencyInfo {
  const found = ALL_CURRENCIES.find((c) => c.code.toUpperCase() === code.toUpperCase());
  return found || { code: 'USD', name: 'US Dollar', symbol: '$', rate: 1.0 };
}

/**
 * Format any USD base amount into the target currency with correct symbol and decimal placement.
 */
export function formatMoney(
  baseUsdAmount: number,
  currencyCode: string = 'USD',
  decimals = 2,
): string {
  const cur = getCurrencyInfo(currencyCode);
  const converted = baseUsdAmount * cur.rate;

  const formatted = converted.toLocaleString('en-US', {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  });

  return `${cur.symbol} ${formatted}`;
}
