/**
 * Local development seed. NEVER run this against a deployed database.
 *
 * Creates a real account with a real PBKDF2 password hash, plus generic example companies
 * (Company A, Company B, Workspace A) and a pending invitation, so the Personal Account and
 * Security screens can be reviewed with content produced by the real code paths.
 *
 *   node db/dev-seed.mjs > .dev-seed.sql
 *   npx wrangler d1 execute DB --local --persist-to .wrangler/state \
 *     --config dist/server/wrangler.json --file .dev-seed.sql
 *
 * Sign in locally as developer@erpfy.test / erpfy-local-dev-password
 */

import crypto from 'node:crypto';

const EMAIL = 'developer@erpfy.test';
const PASSWORD = 'erpfy-local-dev-password';
const ACCOUNT = 'dev-local-account';
const COLLEAGUE = 'dev-colleague';

// Must match hashPassword() in lib/core/crypto.ts.
const ITERATIONS = 210_000;
const salt = crypto.randomBytes(16);
const hash = crypto.pbkdf2Sync(PASSWORD, salt, ITERATIONS, 32, 'sha256');
const passwordHash = `pbkdf2-sha256$${ITERATIONS}$${salt.toString('base64')}$${hash.toString('base64')}`;

const now = Date.now();
const day = 86_400_000;

const lines = [
  `-- Generated by db/dev-seed.mjs at ${new Date(now).toISOString()}. Local development only.`,
  `DELETE FROM core_recovery_codes WHERE account_id IN ('${ACCOUNT}','${COLLEAGUE}');`,
  `DELETE FROM core_totp WHERE account_id IN ('${ACCOUNT}','${COLLEAGUE}');`,
  `DELETE FROM core_login_challenges WHERE account_id IN ('${ACCOUNT}','${COLLEAGUE}');`,
  `DELETE FROM core_sessions WHERE account_id IN ('${ACCOUNT}','${COLLEAGUE}');`,
  `DELETE FROM core_one_time_tokens WHERE account_id IN ('${ACCOUNT}','${COLLEAGUE}');`,
  `DELETE FROM core_credentials WHERE account_id IN ('${ACCOUNT}','${COLLEAGUE}');`,
  `DELETE FROM core_activity_events WHERE account_id IN ('${ACCOUNT}','${COLLEAGUE}');`,
  `DELETE FROM core_favorites WHERE account_id = '${ACCOUNT}';`,
  `DELETE FROM core_company_visits WHERE account_id = '${ACCOUNT}';`,
  `DELETE FROM core_invitations WHERE email = '${EMAIL}';`,
  `DELETE FROM core_memberships WHERE account_id IN ('${ACCOUNT}','${COLLEAGUE}');`,
  // Also clear anything any other account left pointing at the seeded companies, or the
  // foreign keys will refuse the delete.
  `DELETE FROM core_activity_events WHERE company_id IN ('dev-company-a','dev-company-b','dev-workspace-a','dev-outsider');`,
  `DELETE FROM core_favorites WHERE company_id IN ('dev-company-a','dev-company-b','dev-workspace-a','dev-outsider');`,
  `DELETE FROM core_company_visits WHERE company_id IN ('dev-company-a','dev-company-b','dev-workspace-a','dev-outsider');`,
  `DELETE FROM core_invitations WHERE company_id IN ('dev-company-a','dev-company-b','dev-workspace-a','dev-outsider');`,
  `DELETE FROM core_memberships WHERE company_id IN ('dev-company-a','dev-company-b','dev-workspace-a','dev-outsider');`,
  `DELETE FROM core_companies WHERE id IN ('dev-company-a','dev-company-b','dev-workspace-a','dev-outsider');`,
  `DELETE FROM core_account_preferences WHERE account_id IN ('${ACCOUNT}','${COLLEAGUE}');`,
  `DELETE FROM core_accounts WHERE id IN ('${ACCOUNT}','${COLLEAGUE}');`,

  `INSERT INTO core_accounts (id,email,display_name,timezone,created_at,last_seen_at,email_verified_at)
   VALUES ('${ACCOUNT}','${EMAIL}','Local Developer','Europe/London',${now - 30 * day},${now},${now - 30 * day});`,
  `INSERT INTO core_accounts (id,email,display_name,timezone,created_at,last_seen_at,email_verified_at)
   VALUES ('${COLLEAGUE}','colleague@erpfy.test','Sam Rivera','Europe/London',${now - 40 * day},${now - day},${now - 40 * day});`,
  `INSERT INTO core_credentials (account_id,password_hash,password_updated_at,failed_attempts,locked_until)
   VALUES ('${ACCOUNT}','${passwordHash}',${now - 30 * day},0,0);`,

  `INSERT INTO core_companies
     (id,name,slug,country_code,currency,timezone,language,sector_slug,industry_slug,
      business_models,employee_band,plan,state,trial_ends_at,onboarding_state,onboarding_steps,
      created_at,created_by,request_key)
   VALUES
     ('dev-company-a','Company A','company-a','GB','GBP','Europe/London','en','retail-ecommerce','general-retail','["B2C","Retail"]','6–20','growth','trial',${now + 9 * day},'completed','{}',${now - 20 * day},'${ACCOUNT}','seed-a'),
     ('dev-company-b','Company B','company-b','PK','PKR','Asia/Karachi','en','wholesale-distribution','distribution-networks','["B2B","Distribution"]','21–50','starter','trial',${now + 3 * day},'in_progress','{}',${now - 6 * day},'${ACCOUNT}','seed-b'),
     ('dev-workspace-a','Workspace A','workspace-a','AE','AED','Asia/Dubai','en','professional-services','consulting','["B2B","Services"]','2–5','starter','trial',${now + 12 * day},'completed','{}',${now - 2 * day},'${COLLEAGUE}','seed-c'),
     ('dev-outsider','Outsider Ltd','outsider','GB','GBP','Europe/London','en','','','[]','','starter','trial',${now + 20 * day},'completed','{}',${now - day},'${COLLEAGUE}','seed-outsider');`,

  `INSERT INTO core_memberships (company_id,account_id,role,status,branch_scope,joined_at)
   VALUES
     ('dev-company-a','${ACCOUNT}','owner','active','',${now - 20 * day}),
     ('dev-company-b','${ACCOUNT}','administrator','active','',${now - 6 * day}),
     ('dev-workspace-a','${COLLEAGUE}','owner','active','',${now - 2 * day}),
     ('dev-outsider','${COLLEAGUE}','owner','active','',${now - day});`,

  `INSERT INTO core_company_visits (account_id,company_id,last_opened_at)
   VALUES ('${ACCOUNT}','dev-company-a',${now - 3_600_000}),('${ACCOUNT}','dev-company-b',${now - 3 * day});`,

  `INSERT INTO core_favorites (account_id,company_id,created_at)
   VALUES ('${ACCOUNT}','dev-company-a',${now - 5 * day});`,

  `INSERT INTO core_invitations (id,company_id,email,role,status,invited_by,message,created_at,expires_at,responded_at)
   VALUES ('dev-invite-1','dev-workspace-a','${EMAIL}','member','pending','${COLLEAGUE}',
   'Joining you to the consulting workspace so you can see the client list.',${now - day},${now + 13 * day},NULL);`,
];

process.stdout.write(lines.join('\n') + '\n');
